name: simple_day
description: Simple Day - personal daily task manager
publish_to: 'none' # не публикуем в pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Работа с датами и локалью
  intl: ^0.18.1

  # Локальное хранилище
  shared_preferences: ^2.2.2

  # Уведомления
  flutter_local_notifications: ^14.1.5

  # Таймзоны (нужно для планирования уведомлений)
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
